apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helpdesk-backend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
spec:
  ingressClassName: nginx
  rules:
    - host: api.helpdesk.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: helpdesk-backend
                port:
                  number: 80
